### ISSUE TITLE
Request: Fully enabling/disabling RPC

### ISSUE THREAD

**Issue by NaamloosDT** [Swan/DiscordRPCVS#11]
I'd like to be able to disable the rich presence when working on e.g. secret projects or when I'm listening to music with rich presences. Is that doable?

If you're okay with it, I might consider contributing myself.

**Comment by Swan** [comment]
Yes, this is possible. If you are going to contribute, you'll want to create another config property and button that shuts down and re-initializes the RPC and have the setting activated upon startup.

**Comment by ThomasAunvik** [comment]
Did it for ya.

**Comment by Swan** [comment]
Added in #15
