### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by IOverheat** [Swan/DiscordRPCVS#14]
i got crashed on startup
![screenshot_1](https://user-images.githubusercontent.com/33429357/38889664-0f7299e4-4288-11e8-8517-185d05a07507.png)
[ActivityLog.zip](https://github.com/Swan/DiscordRPCVS/files/1921155/ActivityLog.zip)

**Comment by ramzialhaddadtm** [comment]
Reinstall the package? And also could you translate the error message

**Comment by IOverheat** [comment]
reinstall isn't work.
And translate:
The 'DiscordRPCVSPackage' package did not load correctly.

The cause of the problem might be a configuration change or other extension installation. For more information, see the file 'C:\Users\toshiba\AppData\Roaming\Microsoft\VisualStudio\15.0_047ca15f\ActivityLog.xml'

Try restarting Visual Studio to fix the problem.

Do you want to continue showing this error message?
-------------------------------------------- Yes - No ----

**Comment by Swan** [comment]
Here's a couple things to try:

1. Delete the `config.json` file located in /Documents/discord_rpc_vs/
2. Restart VS as administrator.

**Comment by IOverheat** [comment]
Deleting the config.json is worked

**Comment by Swan** [comment]
@IOverheat Do you still have the file perhaps in your recycle bin? Forgot to ask, but I'd like to investigate the cause.

**Comment by IOverheat** [comment]
Yes, Here is 
[config.zip](https://github.com/Swan/DiscordRPCVS/files/1924676/config.zip)
