### ISSUE TITLE
[Feature Request] Display options

### ISSUE THREAD

**Issue by diondokter** [Swan/DiscordRPCVS#2]
It would be nice to be able to toggle whether the filename (and time spent in that page) is shown.
You might want to share which project you're working on, but not the contents of that project.

Also, when working on a project that has a public git repository, a link to that repository could also be shown.

**Comment by Swan** [comment]
I have gone ahead and implemented that for you. After updating the extension, you should have a new set of menu commands that allow you to toggle the file name, solution, and timestamp.

**Example:**
<p> <img src="https://eggplants.org/lsmcbc.png"></p>

Feel free to open up another issue if you have any other requests/modifications.
