### ISSUE TITLE
Configuration File

### ISSUE THREAD

**Issue by NCSGeek** [Swan/DiscordRPCVS#21]
Could we have an option to change the config file location? It bugs be to have it's own folder and file in my documents.

**Comment by FurkanKambay** [comment]
@NCSGeek I'm thinking on working on this soon, I'm assuming you haven't had the time because you don't have a fork?

**Comment by NCSGeek** [comment]
@FurkanKambay I copied it locally and tinkered around for a few minutes. I dont have the time right now for working on it seriously, so yup please feel free to work on that. I'd love for this to be a feature.
