### ISSUE TITLE
Support for Markdown?

### ISSUE THREAD

**Issue by Macley-Kun** [Swan/DiscordRPCVS#26]
I was working with a .md file, and noticed my status:
![image](https://user-images.githubusercontent.com/26381427/48673926-02624480-eb47-11e8-8a6c-d27f49f04eec.png)
I looked up on google, and found the following:
https://www.google.nl/search?q=markdown+language+logo&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiD-u_tk97eAhXMfFAKHaZjCU4Q_AUIDigB&biw=838&bih=911
Is it maybe possible to also add an icon for this?

Thanks for making this plugin! Love it <3

**Comment by FurkanKambay** [comment]
[Here](https://github.com/topics/markdown-editor) GitHub uses [this icon](https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/markdown/markdown.png).

Do you have other language suggestions? We should probably do it in batch.

**Comment by Macley-Kun** [comment]
Mmm not at the moment but I could do a google search and find all the types of programming file extensions, test them out, and then report those results, will take a while but would complete this extension.
I’ll start working on it today.

**Comment by Macley-Kun** [comment]
[ListofFileExtensions.xlsx](https://github.com/Swan/DiscordRPCVS/files/2716256/ListofFileExtensions.xlsx)
So i made this excelsheet, the data is from https://www.online-convert.com/file-type and i added some stuff to make progress a little easier.

I didn't bother to remove the formats i think wouldn't even be supported/editted in VS, but i rather hear from someone else what they think about that.

I/someone could host this sheet in Google, but i'm not a fan of their excel :P, hope ya like the sheet.

**Comment by FurkanKambay** [comment]
@Macley-Kun you probably shouldn't have struggled with that, lol. From the list, we only mostly only care about the "Developer file formats" and probably not even most of them, I think.

I was actually gonna open a PR for improving the languages, extension matching etc. I forgot about it after I opened #25. I can add some languages alongside those improvements if I decide to do it. I'll probably take a look tomorrow.

**Comment by Macley-Kun** [comment]
Wasn’t that much work haha! You can maybe spit trough that file and delete the rows that aren’t needed :-)

**Comment by Macley-Kun** [comment]
Any update on this?

**Comment by Macley-Kun** [comment]
:P update?

**Comment by Macley-Kun** [comment]
I'm gonna close this one, i don't think this is gonna be fufilled anytime soon. I no longer use vs anyways, feel free to re-open or create a new issue! 👍
