### ISSUE TITLE
[Feature Request] Reset of Timestamp

### ISSUE THREAD

**Issue by AdrienBourgois** [Swan/DiscordRPCVS#3]
It could be cool to choose between a reset of the timestamp for switching file (like actually implemented) or for switching solution, because if we want to quickly look to an another file, the timestamp go back to zero.

**Comment by EthanC** [comment]
+1, would really love this- only thing this Extension is missing right now 😄

**Comment by nathan130200** [comment]
Same, i don't like the time reset. :\

**Comment by Swan** [comment]
I'll have a toggle for this in the next release. Stay tuned.

**Comment by Swan** [comment]
Hi guys,

I have completed your request and added a toggle for resetting the timestamp. You should have a new button in your tools menu bar.

<p><img src="https://eggplants.org/5milpp.png"></p>


As always, feel free to open up another issue if you find any problems or want any more features.
