### ISSUE TITLE
Discord does not show editing of .c files

### ISSUE THREAD

**Issue by Alereon** [Swan/DiscordRPCVS#6]
It seems like discord does not recognize .c files when editing them.
As far as I can tell, .c files should be supported?
See the screenshots below.

![xywswja](https://user-images.githubusercontent.com/21091889/34669048-3fb417a6-f470-11e7-9c6a-9489dfbe802b.png)
![2tjcxdp](https://user-images.githubusercontent.com/21091889/34669065-4b0ecc9a-f470-11e7-8c30-f5754547bb22.png)

**Comment by Swan** [comment]
I have updated the extension. C files should work, and header files should display an icon as well.

Feel free to open up another issue if anything.
