### ISSUE TITLE
Debugging: crash when opening project

### ISSUE THREAD

**Issue by BenjaVR** [Swan/DiscordRPCVS#7]
Forked the project. When I start a debug session and I open a project in the new VS instance, and exception gets thrown:
![image](https://user-images.githubusercontent.com/17981138/34711594-35c9e56c-f520-11e7-9395-934f5532e511.png)

I did not change anything, and have no idea where to look to resolve this issue. Maybe I am just doing something wrong.

To start debugging I changed 2 values in the project properties:
![image](https://user-images.githubusercontent.com/17981138/34711641-697b586e-f520-11e7-916f-6f0924b89cf4.png)

**Comment by Swan** [comment]
Interesting. I can't reproduce. Have you tried starting without debugging (CTRL + F5)?

**Comment by BenjaVR** [comment]
Tried without debugging and no crash.

I see the `windowActivated.Document` is null here:
![image](https://user-images.githubusercontent.com/17981138/34730467-cd78b066-f55f-11e7-82a6-95fbf02170b2.png)

**Comment by Swan** [comment]
I'll have to investigate more why that happens, but I'm sure it's an issue with DTE (as it is known to have issues similar to this).
