### ISSUE TITLE
Package not loading correctly

### ISSUE THREAD

**Issue by ramzialhaddadtm** [Swan/DiscordRPCVS#8]
So recently I've been launching VS and I get this message box
![uh oh](https://user-images.githubusercontent.com/5371012/35566479-fd83a492-05da-11e8-87ed-18d3bcf4d529.PNG)

Then when I check the activity log and Ctrl+F for discord I get this chunk of code
`<entry>
    <record>555</record>
    <time>2018/01/30 12:27:08.777</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [DiscordRPCVSPackage]</description>
    <guid>{EA99CD90-97EA-40A5-BE3C-2F3377242800}</guid>
  </entry>
  <entry>
    <record>556</record>
    <time>2018/01/30 12:27:08.864</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [DiscordRPCVSPackage]Source: &apos;discord-rpc-vs&apos; Description: Object reference not set to an instance of an object.&#x000D;&#x000A;System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at discord_rpc_vs.Config.Configuration.Deserialize() in C:\Users\swan\Desktop\Stuff\Git\discord-rpc-vs\discord-rpc-vs\Config\Configuration.cs:line 62&#x000D;&#x000A;   at discord_rpc_vs.DiscordRPCVSPackage.Initialize() in C:\Users\swan\Desktop\Stuff\Git\discord-rpc-vs\discord-rpc-vs\DiscordRPCVSPackage.cs:line 125&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)</description>
    <guid>{EA99CD90-97EA-40A5-BE3C-2F3377242800}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>557</record>
    <time>2018/01/30 12:27:08.876</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [DiscordRPCVSPackage](null)</description>
    <guid>{EA99CD90-97EA-40A5-BE3C-2F3377242800}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>558</record>
    <time>2018/01/30 12:27:08.877</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [DiscordRPCVSPackage]</description>
    <guid>{EA99CD90-97EA-40A5-BE3C-2F3377242800}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo></errorinfo>
  </entry>`

What does this mean?

**Comment by Swan** [comment]
This seems to be an issue with your config not being loaded correctly. Can you check your documents folder and in the "discord_rpc_vs" folder  and post your config.json file?

**Comment by Swan** [comment]
Delete the file then restart Visual Studio, and see if that helps.

**Comment by ramzialhaddadtm** [comment]
ok ill try that as soon as I can

**Comment by ramzialhaddadtm** [comment]
Yeah it works fine thanks!

**Comment by Swan** [comment]
Glad to hear. Feel free to open up another issue if you have any other questions or concerns.
